In [ ]:
from tensorflow import keras

new_model = keras.models.load_model("mnist-model.h5")

In [ ]:
new_model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 128)               100480    
                                                                 
 dense_1 (Dense)             (None, 128)               16512     
                                                                 
 dense_2 (Dense)             (None, 64)                8256      
                                                                 
 dense_3 (Dense)             (None, 10)                650       
                                                                 
Total params: 125,898
Trainable params: 125,898
Non-trainable params: 0
_________________________________________________________________


In [ ]:
import numpy as np
import cv2

In [ ]:
np.set_printoptions(precision=None, threshold=None, edgeitems=None, linewidth=180, suppress=None)


In [ ]:
image_path = "test.png"
grey_image = cv2.cvtColor(cv2.imread(image_path), cv2.COLOR_BGR2GRAY)
img = np.invert(cv2.resize(grey_image,(28,28)))
print(img)
test_img = img.reshape((1,784))

[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0  60 179 194 173  39   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   2 213 255 255 255 255 255   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0 163 255 255 255 255 255 253   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0  60 255 255 255 205   8 100   4   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0 226 255 255 197   0   0   0   0   0   0   0   0   

In [ ]:
prediction = new_model.predict(test_img)[0]
classname = np.argmax(prediction)
print("Class: ",classname)

probability = prediction[classname]
print("Confidence: ",probability)

Class:  4
Confidence:  0.73664945
